# Generated by Django 4.1.3 on 2022-11-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='id',
        ),
        migrations.AddField(
            model_name='data',
            name='plz',
            field=models.IntegerField(default=8160, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
